version: 2.1
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: echo
          command: ls -lh
      - run: 
          name: install npm dependencies
          command: npm install --save
      - run:
          name: run tests
          command: ./node_modules/mocha/bin/mocha test/ --reporter-options reportDir=test-results,reportFilename=test-results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
# Orchestrate our job run sequence
workflows:
  build_test:
    jobs:
      - build